UPDATE tasks
SET status = CASE status
  WHEN 'TODO' THEN 'TO_DO'
  WHEN 'IN_PLANNING' THEN 'TO_DO'
  WHEN 'READY_TO_IMPLEMENT' THEN 'TO_DO'
  WHEN 'IN_WORK' THEN 'TO_AGENT'
  WHEN 'WAIT_REVIEW' THEN 'TO_REVIEW'
  WHEN 'READY_TO_DEPLOY' THEN 'TO_DEPLOY'
  WHEN 'DONE' THEN 'DONE'
END
WHERE status IN (
  'TODO',
  'IN_PLANNING',
  'READY_TO_IMPLEMENT',
  'IN_WORK',
  'WAIT_REVIEW',
  'READY_TO_DEPLOY',
  'DONE'
);
